scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'crm'
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: 'docStore'
      - targets: [ 'host.docker.internal:8085' ]
        labels:
          application: 'analytics'
      - targets: [ 'host.docker.internal:8083' ]
        labels:
          application: 'communicationmngr'