server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

  # local machine logs

    # Logs from /var/log/crm directory
  - job_name: crm
    static_configs:
      - targets:
          - localhost
        labels:
          job: crm
          __path__: /var/log/crm/*.log

  # Logs from /var/log/communicationmngr directory
  - job_name: communicationmngr
    static_configs:
      - targets:
          - localhost
        labels:
          job: communicationmngr
          __path__: /var/log/communicationmngr/*.log

  # Logs from /var/log/analytics directory
  - job_name: analytics
    static_configs:
      - targets:
          - localhost
        labels:
          job: analytics
          __path__: /var/log/analytics/*.log

  # Logs from /var/log/doc_store directory
  - job_name: doc_store
    static_configs:
      - targets:
          - localhost
        labels:
          job: doc_store
          __path__: /var/log/doc_store/*.log


## docker logs

#- job_name: docker
#  pipeline_stages:
#    - docker: {}
#  static_configs:
#    - labels:
#        job: docker
#        __path__: /var/lib/docker/containers/*/*-json.log

# syslog target

#- job_name: syslog
#  syslog:
#    listen_address: 0.0.0.0:1514 # make sure you also expose this port on the container
#    idle_timeout: 60s
#    label_structured_data: yes
#    labels:
#      job: "syslog"
#  relabel_configs:
#    - source_labels: ['__syslog_message_hostname']
#      target_label: 'host'