spring:
  application:
    name: analytics
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/crm

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
