spring:
  application:
    name: document_store
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/crm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
